language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython coinor-libosi-dev coinor-libcbc-dev 
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install . --use-mirrors"
script: python test.py
