language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq coinor-libcbc0
install: "pip install -r requirements.txt --use-mirrors"
script: test.py
